name: build

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'LICENSE'
      - '**/*.md'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'LICENSE'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install imagemagick
        run: sudo apt-get install -y imagemagick

      - name: Allow ImageMagick PDF conversion
        run: sudo sed -i 's/policy domain="coder" rights="none" pattern="PDF"/policy domain="coder" rights="read | write" pattern="PDF"'/ /etc/ImageMagick-6/policy.xml

      - run: npm clean-install .
      - run: npm run lint
      - run: npm run test
      - run: npm run build
