name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write   # create GitHub Release and upload assets

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install imagemagick
        run: sudo apt-get install -y imagemagick

      - name: Allow ImageMagick PDF conversion
        run: sudo sed -i 's/policy domain="coder" rights="none" pattern="PDF"/policy domain="coder" rights="read | write" pattern="PDF"'/ /etc/ImageMagick-6/policy.xml

      - run: npm clean-install .
      - run: npm run test
      - run: npm run build
      - run: ./makedeb.sh

      - name: Get .deb package name
        run: echo "PACKAGE_NAME=$(ls ./debian/*.deb)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PACKAGE_NAME }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
